# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        EsqueletBundle\Entity\Usuario:
          algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: pepe
                        roles: 'ROLE_ADMIN'
        my_db_provider:
          entity:
              class: EsqueletBundle:usuario
              property: username
    access_control:
            - { path: ^/usuarios/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/usuarios, roles: ROLE_ADMIN }
            - { path: ^/carlet/crud, roles: ROLE_ADMIN }
            - { path: ^/examen, roles: ROLE_ADMIN }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            http_basic: ~

        usuarios:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: /usuarios/login
                check_path: /usuarios/login
            logout:
                path:   /usuarios/logout
                target: /

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
